spring.datasource.url=jdbc:postgresql://localhost:5432/transport
spring.datasource.username=transport
spring.datasource.password=transport_dev

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
