CREATE TABLE stations
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pkp_id        BIGINT                   NOT NULL,
    name          VARCHAR(255)             NOT NULL,
    active        BOOLEAN                  NOT NULL DEFAULT TRUE,
    last_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_stations PRIMARY KEY (id),
    CONSTRAINT uk_stations_pkp_id UNIQUE (pkp_id)
);

