CREATE TABLE railway_carriers
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code          VARCHAR(30)                               NOT NULL,
    name          VARCHAR(255)                              NOT NULL,
    valid_from    TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    valid_to      TIMESTAMP WITHOUT TIME ZONE               NOT NULL,
    active        BOOLEAN                                   NOT NULL DEFAULT TRUE,
    last_modified TIMESTAMP WITH TIME ZONE                  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_railway_carriers PRIMARY KEY (id),
    CONSTRAINT uk_railway_carriers_code UNIQUE (code)
);

