CREATE TABLE railway_commercial_categories
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                VARCHAR(100)             NOT NULL,
    name                VARCHAR(255)             NOT NULL,
    carrier_code        VARCHAR(50)              NOT NULL,
    speed_category_code VARCHAR(50)              NOT NULL,
    active              BOOLEAN                  NOT NULL DEFAULT TRUE,
    last_modified       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_railway_commercial_categories PRIMARY KEY (id),
    CONSTRAINT uk_railway_commercial_categories_code_carrier UNIQUE (code, carrier_code)
);

CREATE INDEX idx_railway_commercial_categories_carrier_code ON railway_commercial_categories (carrier_code);
