CREATE TABLE railway_stop_types
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    pkp_id        BIGINT                   NOT NULL,
    description   VARCHAR(255)             NOT NULL,
    active        BOOLEAN                  NOT NULL DEFAULT TRUE,
    last_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_railway_stop_types PRIMARY KEY (id),
    CONSTRAINT uk_railway_stop_types_pkp_id UNIQUE (pkp_id)
);
