CREATE TABLE railway_city_station_groups
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255)             NOT NULL,
    active        BOOLEAN                  NOT NULL DEFAULT TRUE,
    last_modified TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_railway_city_station_groups PRIMARY KEY (id),
    CONSTRAINT uk_railway_city_station_groups_name UNIQUE (name)
);

CREATE TABLE railway_city_station_group_members
(
    station_id            BIGINT NOT NULL,
    city_station_group_id BIGINT NOT NULL,

    CONSTRAINT pk_railway_city_station_group_members PRIMARY KEY (station_id),
    CONSTRAINT fk_city_station_group_members_station FOREIGN KEY (station_id) REFERENCES railway_stations (id),
    CONSTRAINT fk_city_station_group_members_group FOREIGN KEY (city_station_group_id) REFERENCES railway_city_station_groups (id) ON DELETE CASCADE
);

CREATE INDEX idx_city_station_group_members_group_id ON railway_city_station_group_members (city_station_group_id);
